services:

  postgres:
    image: postgres:17
    container_name: tickera-postgres

    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - compute_query_id=on

    environment:
      POSTGRES_DB: tickera
      POSTGRES_USER: tickera
      POSTGRES_PASSWORD: tickera

    ports:
      - "5436:5432"

    volumes:
      - tickera_postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7.4-alpine
    container_name: tickera-redis

    ports:
      - "6380:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - tickera_redis_data:/data


  kafka:
    image: apache/kafka:4.1.1
    container_name: tickera-kafka

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - tickera_kafka_data:/var/lib/kafka/data


  prometheus:
    image: prom/prometheus:latest
    container_name: tickera-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"


  grafana:
    image: grafana/grafana:latest
    container_name: tickera-grafana

    ports:
      - "3000:3000"

    volumes:
      - tickera_grafana_data:/var/lib/grafana


volumes:
  tickera_postgres_data:
  tickera_redis_data:
  tickera_kafka_data:
  tickera_grafana_data: