spring:
  application:
    name: tickera

  datasource:
    url: jdbc:postgresql://localhost:5436/tickera
    username: tickera
    password: tickera

    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6380
      connect-timeout: 2s
      timeout: 2s

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

tickera:
  seat-hold:
    duration: 2m